# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1801173cbbe5ce67aeebe395135a7996814dd3ba535fbe14b64f858825bcadd5336c5f19ee0409b95f71d7b6ec936dc31af3beb1a5d6c3a857450091ec9c2e72

test:
  secret_key_base: f748bbd4329d74598fe673b9c6f8fcac174b8928f331a03536f868d9970db27c9ffdce7e47ac42eda293105e8b2b5a88c9eaff1652448d42c285b26d579dcc41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
