# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 219ed725899a6835d3fc6eaba50968ae85b6d357f0d5b25815d4641876050be43059842c5ba273d0d3a8633aa089e891283bf082d45c6b6854a54e5503811b21

test:
  secret_key_base: 78ebd7e37d0c5e22d2dc93a58182b34d12cdb72cebe582a051831ff85abdede5eccdb1347557ebf721335caf8b6fb7a337f621964ef02479b7a0f537a4b5ff29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
