# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339af308ffe702cc1b2e4628231c5d33258b8f37cc193a6902b942e42b3a09153764a8d00c648eda33e2acc46ac2c0898f902dc3ec6406d27f6151fc36d9ff4e

test:
  secret_key_base: fe79bef8d27b8581c33e8b758f191bb1db4674e4cd1c24a1aa0bb2c5619f848db5bc2bc16955c2fee3af466b4f776f7190d62bc966258ca8e9e89b1f07677706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
