# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8128b859ecb4fa1ad2eee85ce791accba15b270758fa470be6fe0135d54f8cc6be9611ac33204bf959869d5a8bbc99d4cf86f779b90ac4671f80b2d19f7431a

test:
  secret_key_base: 1ca5b2521cd20611762ba08562a983f4374d9b90b79fb969eed97428a3e393e35f8afb063abbfebd16a46961adf25c66a4d9368303cb5310e4ce979ad0718179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
