# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 201091e2a4f3714ef4f21fdd57467287b917420a9c4050c2a45760c50da468a95d388f3d74b8393fc3d570b7a3f46fb2260d4a24910819450a5a9b12ce4f1987

test:
  secret_key_base: 3d0b02bd39c920a150848a2440bafc71a52322c6e16f3e6b0fdc55316ba67e381160b564ca0ecb7cf5ddcd70c737168acde49891500dca68f2b370858679c89b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
