# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a86ccf2f192c8094a9bb9ef112d03509390410d5837a4a915c1a0dcc6e945f33f12bb44c4be624a126967cd0d853890bbc1aab22618013aab6a6246c12989140

test:
  secret_key_base: 0898da265e9552b481a3979c2cbcdae66ee73cda2a6554ab1f4d41383baaa2bace59e5021b4b41dd82cb5921484a74e3d96432a65bf2ffa7eba5030b464b03b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
